name = "HerbBenchmarks"
uuid = "eadf8b74-d38a-4b1a-a063-8d36e493d376"
authors = ["jaapjong <J.deJong-18@student.tudelft.nl>", "Tilman Hinnerichs <t.r.hinnerichs@tudelft.nl>", "Sebastijan Dumancic <s.dumancic@tudelft.nl>"]
version = "0.1.0"

[deps]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
HerbCore = "2b23ba43-8213-43cb-b5ea-38c12b45bd45"
HerbData = "495a3ad3-8034-41b3-a087-aacf2fd71098"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
HerbCore = "0.1.0"
HerbData = "0.1.0"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
